# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qJ40GWVXqSKzv6RIxO3VuZMOuOUPJ8H
"""

import numpy as np
import pandas as pd
data=pd.read_csv("/content/Mall_Customers.csv")
print(data)

df=pd.DataFrame(data)
print(df)

x=data.iloc[:,[3,4]].values
print(x)


missing=df.dropna()
print(missing)

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
wcss_list=[]
for i in range(1,11):
    kmeans=KMeans(n_clusters=i,init='k-means++',random_state=5)
    kmeans.fit(x)
    wcss_list.append(kmeans.inertia_)
plt.plot(range(1,11),wcss_list)
plt.title("The Elbow Graph")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()

kmeans=KMeans(n_clusters=5,init='k-means++',random_state=5)
y_pred=kmeans.fit_predict(x)
print(y_pred)

plt.scatter(x[y_pred==0,0],x[y_pred==0,1],s=100,c='red',label='Cluster1')
plt.scatter(x[y_pred==1,0],x[y_pred==1,1],s=100,c='blue',label='Cluster2')
plt.scatter(x[y_pred==2,0],x[y_pred==2,1],s=100,c='green',label='Cluster3')
plt.scatter(x[y_pred==3,0],x[y_pred==3,1],s=100,c='cyan',label='Cluster4')
plt.scatter(x[y_pred==4,0],x[y_pred==4,1],s=100,c='magenta',label='Cluster5')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=300,c='yellow',label='Centroids')
plt.title("Clusters of Customers")
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.legend()
plt.show()